### ISSUE TITLE
Required token should ideally be scoped

### ISSUE THREAD

**Issue by mthaddon** [niemeyer/discedit#5]
Currently discedit requires a token that is of "user level: single user" but of scope "global key (allows all actions)" per https://github.com/niemeyer/discedit#configure-discedit-with-your-discourse-keys.

This means that if the user in question is an admin, they could potentially use this token to delete or modify other users.

Discourse tokens can be scoped to "topics" with "read" and "write" permissions. However, creating a token with just these permissions didn't seem to work.

Is it possible to update discedit to be able to use scoped tokens?

**Comment by niemeyer** [comment]
It's not possible with the currently available scopes in Discourse unfortunately. Even the basic features such as drafts are not made available through those scopes, and it's impossible to imagine an editing tool that doesn't handle drafts and conflicts appropriately.
